<?php


/**
 * Implements hook_menu()
 */
function hkecho_menu(){
  $items = [];
  
  $items['hkecho'] = array(
      'title' => t(''),
      'page callback' => 'hkecho_page',
      'access callback' => TRUE,
  );
  
  return $items;
}

/**
 * Implements hook_cronapi().
 */
function hkecho_cronapi($op, $job = NULL) {
  $items = array();

  $items['birthdate_and_joiningdate'] = array(
      'description' => 'Get birthdate and joining date from hknext',
      'rule' => '0 0 1 * *',
      'callback' => 'hkecho_save_dates',
      'file' => 'includes/hkecho.cron.inc', // External file, like hook_menu
      'file path' => drupal_get_path('module', 'hkecho')
  );
  return $items;

}

/*
 * Just for fun
 */
function hkecho_page(){
  return theme("hkecho");
}



/**
 * Implements hook_theme().
 */
function hkecho_theme($existing, $type, $theme, $path) {
  
  return array(
      'hkecho' => array(
          'template' => 'hkecho',
          'path' => $path . '/templates',
      ),
  );
}

function _get_echo_data($category, $department = NULL) {
  $vid = taxonomy_vocabulary_machine_name_load('category');
  $terms = taxonomy_get_tree($vid->vid);
  foreach($terms as $item) {
    if(strtolower($item->name) == $category) {
      $c_tid = $item->tid;
    }
  }
  if($department) {
    $vid = taxonomy_vocabulary_machine_name_load('departments');
    $terms = taxonomy_get_tree($vid->vid);
    foreach($terms as $item) {
      if(strtolower($item->name) == $department) {
        $d_tid = $item->tid;
      }
    }
  }
  $query = new EntityFieldQuery();
  $entities = $query->entityCondition('entity_type', 'node', '=')
          ->propertyCondition('type', 'echo')
          ->fieldCondition('field_category', 'tid', $c_tid, '=');
  if ($department) {
    $entities->fieldCondition('field_department', 'tid', $d_tid, '=');
  }
  $query->propertyOrderBy('created', 'DESC');
  $query->range(0, 10);        
  $entities = $query->execute();
  $nodes = node_load_multiple(array_keys($entities['node']));
  return $nodes;
}

function _get_tweets() {
  $query = new EntityFieldQuery();
  $entities = $query->entityCondition('entity_type', 'node', '=')
          ->propertyCondition('type', 'hk_tweet');
  $query->propertyOrderBy('created', 'DESC');
  $query->range(0, 10);        
  $entities = $query->execute();
  $nodes = node_load_multiple(array_keys($entities['node']));
  return $nodes;
}

function _get_dates() {
 $query = db_select('user_information','u'); 
 $query->fields('u',array('name','birth_date','joining_date','department'));
 $query->condition(db_or()->condition('u.birth_date', date('d-m-Y',time()), '=')
         ->condition('u.joining_date', date('d-m-Y',time()), '='));
 $result = $query->execute()->fetchAll();
 return $result;
}