<?php


/**
 * Implements hook_menu()
 */
function hkecho_menu(){
  $items = [];
  
  $items['hkecho'] = array(
      'title' => t(''),
      'page callback' => 'hkecho_page',
      'access callback' => TRUE,
  );
  
  return $items;
}

/**
 * Implements hook_cronapi().
 */
function hkecho_cronapi($op, $job = NULL) {
  $items = array();

  $items['birthdate_and_joiningdate'] = array(
      'description' => 'Get birthdate and joining date from hknext',
      'rule' => '0 0 1 * *',
      'callback' => 'hkecho_save_dates',
      'file' => 'includes/hkecho.cron.inc', // External file, like hook_menu
      'file path' => drupal_get_path('module', 'hkecho')
  );
  return $items;

}

/*
 * Just for fun
 */
function hkecho_page(){
  return theme("hkecho");
}



/**
 * Implements hook_theme().
 */
function hkecho_theme($existing, $type, $theme, $path) {
  
  return array(
      'hkecho' => array(
          'template' => 'hkecho',
          'path' => $path . '/templates',
      ),
  );
}